name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '31 8 * * *'

permissions:
  contents: read

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit
        disable-telemetry: true

    - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Issue automatically marked stale!'
        stale-pr-message: 'Pull request automatically marked stale!'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-close: -1
