name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '31 8 * * *'

permissions:
  contents: read

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit
        disable-telemetry: true

    - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Issue automatically marked stale!'
        stale-pr-message: 'Pull request automatically marked stale!'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-close: -1
